services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: BBDD_DesSistWeb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pablop1184
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d BBDD_DesSistWeb"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .

    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:pablop1184@db:5432/BBDD_DesSistWeb
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: pablop1184
      DB_NAME: BBDD_DesSistWeb
      JWT_SECRET: tu_clave_super_secreta_cambiar_en_produccion_2024



    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: